server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none # update # validate
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_ADDRESS:localhost}:3306/teupet?characterEncoding=UTF-8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class: com.mysql.cj.jdbc.Driver
  application:
    name: AnimalService
